Create a null vector of size 10 but the fifth value which is 1

In [2]:
import numpy as np

vector = np.zeros(10)
vector[4] = 1
vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

Create a vector with values ranging from 10 to 49

In [4]:
vector2 = np.arange(10,50)
vector2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

Reverse a vector (first element becomes last)

In [5]:
vector2_reversed = np.flip(vector2)
vector2_reversed

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
matrix = np.arange(9)
matrix.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Find indices of non-zero elements from [1,2,0,0,4,0]

In [12]:
np.nonzero([1,2,0,0,0,0,0,0,4,0])

(array([0, 1, 8], dtype=int64),)

Create a 3x3 identity matrix

In [15]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Create a 3x3x3 array with random values

In [19]:
np.random.rand(3,3,3)

array([[[0.6984701 , 0.10058928, 0.99437406],
        [0.31212585, 0.34675848, 0.68064846],
        [0.65634464, 0.93408734, 0.48002649]],

       [[0.36824035, 0.20169768, 0.32513989],
        [0.138548  , 0.41488385, 0.38488662],
        [0.93831699, 0.87372025, 0.81225052]],

       [[0.40698344, 0.92137733, 0.85743734],
        [0.46149261, 0.28817753, 0.2962509 ],
        [0.91290705, 0.19876299, 0.090816  ]]])