In [1]:
import numpy as np

Create a custom dtype that describes a color as four unsigned bytes (RGBA).

In [2]:
dt_rgba = np.dtype(('i4', [('r','u1'),('g','u1'),('b','u1'),('a','u1')]))

Multiply a 5x3 matrix by a 3x2 matrix (real matrix product).

In [8]:
np.random.seed(28)
arr1 = np.random.rand(5, 3)
arr2 = np.random.rand(3, 2)
print(np.matmul(arr1, arr2))
print(arr1 @ arr2)

[[0.82908638 0.47473385]
 [0.75733043 0.58323449]
 [0.79818927 0.68549602]
 [1.43497079 0.66457431]
 [0.70393503 0.37087069]]
[[0.82908638 0.47473385]
 [0.75733043 0.58323449]
 [0.79818927 0.68549602]
 [1.43497079 0.66457431]
 [0.70393503 0.37087069]]


Given a 1D array, negate all elements which are between 3 and 8, in place.

In [12]:
vec1 = np.arange(11)
vec1[3:9] = -vec1[3:9]
vec1

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

What is the output of the following script?
```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [17]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10
