In [2]:
import numpy as np

Consider an integer vector Z, which of these expressions are legal?
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [8]:
Z = np.arange(1, 11, dtype=int)
print(Z**Z)
print(2 << Z >> 2)
print(Z < - Z)
print(1j*Z)
print(Z/1/1)
# print(Z < Z > Z) Invalid syntax

[         1          4         27        256       3125      46656
     823543   16777216  387420489 1410065408]
[  1   2   4   8  16  32  64 128 256 512]
[False False False False False False False False False False]
[0. +1.j 0. +2.j 0. +3.j 0. +4.j 0. +5.j 0. +6.j 0. +7.j 0. +8.j 0. +9.j
 0.+10.j]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [18]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\angel\AppData\Local\Temp\ipykernel_15600\3026089356.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\angel\AppData\Local\Temp\ipykernel_15600\3026089356.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\angel\AppData\Local\Temp\ipykernel_15600\3026089356.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


How to round away from zero a float array?

In [27]:
Z = np.random.uniform(-5,5,10)
Z_abs = np.abs(Z)
Z_ceiled = np.ceil(Z_abs)
np.copysign(Z_ceiled, Z)

array([-1., -5.,  5.,  3., -2.,  3., -4., -4.,  5., -5.])